---
services:
  redis:
    container_name: selfhosted-redis
    image: redis/redis-stack:latest
  mailhog:
    container_name: selfhosted-mailhog
    image: mailhog/mailhog:latest
    ports: [ 1025:1025, 8025:8025 ]
  discourse:
    container_name: selfhosted-docker
    build: ./discourse
    ports: [ 3000:3000, 4200:4200 ]
